kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-demo-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.31.1@sha256:cd224d8da58d50907d1dd41d476587643dad2ffd9f6a4d96caf530fb3b9a5956
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "127.0.0.1"
    protocol: TCP